import type { LucideIcon } from "lucide-react";
import {
  Antenna,
  BatteryCharging,
  Box,
  Boxes,
  Building2,
  Cable,
  Check,
  ClipboardList,
  CloudRain,
  CloudSun,
  Flag,
  Gauge,
  GraduationCap,
  Hammer,
  Home,
  MapPin,
  Plug,
  Mountain,
  Radio,
  Shield,
  Signal,
  Sprout,
  Square,
  SunMedium,
  Thermometer,
  Trees,
  Users,
  Wifi,
  Wind,
  Wrench,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  users: Users,
  home: Home,
  school: GraduationCap,
  hammer: Hammer,
  building: Building2,
  sign: MapPin,
  trees: Trees,
  mountain: Mountain,
  cable: Cable,
  wifi: Wifi,
  signal: Signal,
  radio: Radio,
  antenna: Antenna,
  thermo: Thermometer,
  rain: CloudRain,
  wind: Wind,
  sprout: Sprout,
  haze: CloudSun,
  gauge: Gauge,
  sun: SunMedium,
  rays: SunMedium,
  battery: BatteryCharging,
  clipboard: ClipboardList,
  check: Check,
  shield: Shield,
  flag: Flag,
  pin: MapPin,
  wrench: Wrench,
  plug: Plug,
  one: Square,
  few: Box,
  many: Boxes,
};

export function ChoiceIcon({ name }: { name: string }) {
  const Icon = ICONS[name] ?? Gauge;
  return <Icon aria-hidden="true" className="size-5" strokeWidth={1.75} />;
}
